#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;

require __DIR__.'/vendor/autoload.php';

$application = new Application();
$application->add(new TwentyTwo\CodeAnalyser\Autoload\Autoload());
$application->run();

exit(0);